### ISSUE TITLE
insecure MEME path

### ISSUE THREAD

**Issue by wsuplantpathology** [L--U--P--U--S/cassis#1]
Hi:

I was trying to run CASSIS on my linux. I got these message:
```
[ERROR] "/data/chen/software/meme_4.12.0/bin/meme" seems to be an insecure path.

Stopped at /data/chen/software/CASSIS_source/cassis.pl line 480.```

I installed meme version 4.12.0 successfully. What does this mean? How can I solve this problem?
Thanks,
Chongjing

**Comment by lu-p-us** [comment]
Hi Chongjing,

this error message is related to Perl's [taint mode](https://perldoc.perl.org/perlsec.html#Taint-mode). Please try to
- remove the dots from your meme path (the directory before the actual file name)
or
- adjust the regex in line 474 to allow dots in the path.

Hope this resolves your problem.
Thomas

**Comment by wsuplantpathology** [comment]
Hi @L--U--P--U--S :

It's tricky. I re-installed meme and removed the dots from meme path following your suggestions, now everything works great. Thanks so much. 
By the way, SMIPS and CASSIS are great tools for secondary metabolite analysis :+1: .

Best,
Chongjing

**Comment by lu-p-us** [comment]
You are welcome and thanks for using CASSIS/SMIPS. I'm glad you like the tools.
