### ISSUE TITLE
MEME compatibility

### ISSUE THREAD

**Issue by adarmitage** [L--U--P--U--S/cassis#2]
I can see that you are aware of compatibility issues with meme >v5 and the issue is on the todo list. In the meantime, what version of meme is CASSIS compatible with?

Error:
(5) Running FIMO …
Progress: 191/191
(6) Counting BINDING SITES per promoter …
  motif   frequency
Cannot read from binding sites file "out/g717.t1/g717.t1/fimo/+0_-3/fimo.txt".
No such file or directory at script/cassis.pl line 1519.

**Comment by lu-p-us** [comment]
Should be working at least with MEME suite v4.9.0 and v4.12.0, possibly also versions in between and older ones. You can now find this information in the updated changelog, too.

If you are running MEME v5 or newer, the FIMO output file will be fimo.tsv and not fimo.txt anymore. But also the structure of the file changed, not only the file name. Similar for MEME.

Does downgrading the MEME version solve this problem for you?

**Comment by adarmitage** [comment]
meme 4.12.0 works great, thanks.
